### DevNet Public
GET http://localhost:4000/v0/fetch HTTP/1.1
content-type: application/json

{
    "provider": "devnet",
    "mode": "public",
    "root": "GOF9GMUIOXHOWFLDWXLHNYUUVTAATXUM9XETNATRDCCOJUD9BUISAZSHUCIWIOKXFHYQXORUNSPALUMIF",
    "dataType": "trytes"
}

### MainNet Private
GET http://localhost:4000/v0/fetch HTTP/1.1
content-type: application/json

{
    "provider": "mainnet",
    "mode": "private",
    "root": "PUGCDPTVRLGCIEMYYNOR9PZ9HBFIPDUJCACKSHNIOGMDXRMYITKGGCR9GJCXOVDIWNUUVXKIGJELWPQPF",
    "dataType": "text"
}


### Provider Restricted
GET http://localhost:4000/v0/fetch HTTP/1.1
content-type: application/json

{
    "provider": "https://nodes.iota.cafe:443",
    "depth": 3,
    "mwm": 14,
    "mode": "restricted",
    "key": "ABCDEFG",
    "root": "GGBRHMCZFTZZITMBTOBUMM9MWDVMTAJZUZARMJFNHY9VRSYZNKMUXTESZETWWHKHONMCZGJYS9PBZQILT",
    "dataType": "json"
}

